<?php
header('Content-type: application/vnd.ms-excel;');
header("Content-Disposition: attachment; filename=Reporte seguimiento cancer " . date("d_m_Y") . ".xls");
header("Pragma: no-cache");
header("Expires: 0");

$json = $_GET['json'];

require_once('../config/dbcon_prod.php');
$cursor = oci_new_cursor($c);
$consulta = oci_parse($c, 'BEGIN PQ_GENESIS_CAC_ORI.P_EXPORTAR_CAC_CANCER(:v_pjson_row_in,:v_ref_cur); end;');
oci_bind_by_name($consulta, ':v_pjson_row_in', $json);
$curs = oci_new_cursor($c);
oci_bind_by_name($consulta, ':v_ref_cur', $curs, -1, OCI_B_CURSOR);
oci_execute($consulta);
oci_execute($curs);
?>

<table border="1" cellpadding="2" cellspacing="0" width="100">
    <tbody>
        <tr align='center'>
            <h2>Reporte seguimiento cancer</h2>
        </tr>
        <tr>
            <th align='center'>V1</th>
            <th align='center'>V2</th>
            <th align='center'>V3</th>
            <th align='center'>V4</th>
            <th align='center'>V5</th>
            <th align='center'>V6</th>
            <th align='center'>V7</th>
            <th align='center'>V8</th>
            <th align='center'>V9</th>
            <th align='center'>V10</th>
            <th align='center'>V11</th>
            <th align='center'>V12</th>
            <th align='center'>V13</th>
            <th align='center'>V14</th>
            <th align='center'>V15</th>
            <th align='center'>V16</th>
            <th align='center'>V17</th>
            <th align='center'>V18</th>
            <th align='center'>V19</th>
            <th align='center'>V20</th>
            <th align='center'>V21</th>
            <th align='center'>V22</th>
            <th align='center'>V23</th>
            <th align='center'>V24</th>
            <th align='center'>V25</th>
            <th align='center'>V26</th>
            <th align='center'>V27</th>
            <th align='center'>V28</th>
            <th align='center'>V29</th>
            <th align='center'>V30</th>
            <th align='center'>V31</th>
            <th align='center'>V32</th>
            <th align='center'>V33</th>
            <th align='center'>V34</th>
            <th align='center'>V35</th>
            <th align='center'>V36</th>
            <th align='center'>V37</th>
            <th align='center'>V38</th>
            <th align='center'>V39</th>
            <th align='center'>V40</th>
            <th align='center'>V41</th>
            <th align='center'>V42</th>
            <th align='center'>V43</th>
            <th align='center'>V44</th>
            <th align='center'>V45</th>
            <th align='center'>V46</th>
            <th align='center'>V461</th>
            <th align='center'>V462</th>
            <th align='center'>V463</th>
            <th align='center'>V464</th>
            <th align='center'>V465</th>
            <th align='center'>V466</th>
            <th align='center'>V467</th>
            <th align='center'>V468</th>
            <th align='center'>V47</th>
            <th align='center'>V48</th>
            <th align='center'>V49</th>
            <th align='center'>V50</th>
            <th align='center'>V51</th>
            <th align='center'>V52</th>
            <th align='center'>V53</th>
            <th align='center'>V531</th>
            <th align='center'>V532</th>
            <th align='center'>V533</th>
            <th align='center'>V534</th>
            <th align='center'>V535</th>
            <th align='center'>V536</th>
            <th align='center'>V537</th>
            <th align='center'>V538</th>
            <th align='center'>V539</th>
            <th align='center'>V54</th>
            <th align='center'>V55</th>
            <th align='center'>V56</th>
            <th align='center'>V57</th>
            <th align='center'>V58</th>
            <th align='center'>V59</th>
            <th align='center'>V60</th>
            <th align='center'>V61</th>
            <th align='center'>V62</th>
            <th align='center'>V63</th>
            <th align='center'>V64</th>
            <th align='center'>V65</th>
            <th align='center'>V66</th>
            <th align='center'>V661</th>
            <th align='center'>V662</th>
            <th align='center'>V663</th>
            <th align='center'>V664</th>
            <th align='center'>V665</th>
            <th align='center'>V666</th>
            <th align='center'>V667</th>
            <th align='center'>V668</th>
            <th align='center'>V669</th>
            <th align='center'>V67</th>
            <th align='center'>V68</th>
            <th align='center'>V69</th>
            <th align='center'>V70</th>
            <th align='center'>V71</th>
            <th align='center'>V72</th>
            <th align='center'>V73</th>
            <th align='center'>V74</th>
            <th align='center'>V75</th>
            <th align='center'>V76</th>
            <th align='center'>V77</th>
            <th align='center'>V78</th>
            <th align='center'>V79</th>
            <th align='center'>V80</th>
            <th align='center'>V81</th>
            <th align='center'>V82</th>
            <th align='center'>V83</th>
            <th align='center'>V84</th>
            <th align='center'>V85</th>
            <th align='center'>V86</th>
            <th align='center'>V87</th>
            <th align='center'>V88</th>
            <th align='center'>V89</th>
            <th align='center'>V90</th>
            <th align='center'>V91</th>
            <th align='center'>V92</th>
            <th align='center'>V93</th>
            <th align='center'>V94</th>
            <th align='center'>V95</th>
            <th align='center'>V96</th>
            <th align='center'>V97</th>
            <th align='center'>V98</th>
            <th align='center'>V99</th>
            <th align='center'>V100</th>
            <th align='center'>V101</th>
            <th align='center'>V102</th>
            <th align='center'>V103</th>
            <th align='center'>V104</th>
            <th align='center'>V105</th>
            <th align='center'>V106</th>
            <th align='center'>V107</th>
            <th align='center'>V108</th>
            <th align='center'>V109</th>
            <th align='center'>V110</th>
            <th align='center'>V111</th>
            <th align='center'>V112</th>
            <th align='center'>V113</th>
            <th align='center'>V114</th>
            <th align='center'>V1141</th>
            <th align='center'>V1142</th>
            <th align='center'>V1143</th>
            <th align='center'>V1144</th>
            <th align='center'>V1145</th>
            <th align='center'>V1146</th>
            <th align='center'>V115</th>
            <th align='center'>V116</th>
            <th align='center'>V117</th>
            <th align='center'>V118</th>
            <th align='center'>V119</th>
            <th align='center'>V120</th>
            <th align='center'>V121</th>
            <th align='center'>V122</th>
            <th align='center'>V123</th>
            <th align='center'>V124</th>
            <th align='center'>V125</th>
            <th align='center'>V126</th>
            <th align='center'>V127</th>
            <th align='center'>V128</th>
            <th align='center'>V129</th>
            <th align='center'>V130</th>
            <th align='center'>V131</th>
            <th align='center'>V132</th>
            <th align='center'>V133</th>
            <th align='center'>V134</th>
            <th align='center'>V135</th>
            <th align='center'>V136</th>
            <th align='center'>V137</th>
            <th align='center'>V138</th>
            <th align='center'>V139</th>
            <th align='center'>V140</th>
            <th align='center'>V141</th>
            <th align='center'>V142</th>
            <th align='center'>V143</th>
            <th align='center'>V144</th>
            <th align='center'>V145</th>
            <th align='center'>V146</th>
            <th align='center'>V147</th>
            <th align='center'>V148</th>
            <th align='center'>V149</th>
            <th align='center'>RESPONSABLE</th>
            <th align='center'>FECHA</th>
            <th align='center'>FECHA</th>
            <th align='center'>CODIGO</th>
            <th align='center'>TIPO</th>

        </tr>
    </tbody>
    <?php
    while (($row = oci_fetch_array($curs, OCI_ASSOC + OCI_RETURN_NULLS)) != false) {
        echo "<tr>";
        echo "<td>";
        echo $row['V1'];
        echo "</td>";
        echo "<td>";
        echo $row['V2'];
        echo "</td>";
        echo "<td>";
        echo $row['V3'];
        echo "</td>";
        echo "<td>";
        echo $row['V4'];
        echo "</td>";
        echo "<td>";
        echo $row['V5'];
        echo "</td>";
        echo "<td>";
        echo $row['V6'];
        echo "</td>";
        echo "<td>";
        echo $row['V7'];
        echo "</td>";
        echo "<td>";
        echo $row['V8'] == "FEMENINO" ? "F" : "M";
        echo "</td>";
        echo "<td>";
        echo $row['V9'];
        echo "</td>";
        echo "<td>";
        echo $row['V10'];
        echo "</td>";
        echo "<td>";
        echo $row['V11'];
        echo "</td>";
        echo "<td>";
        echo $row['V12'];
        echo "</td>";
        echo "<td>";
        echo $row['V13'];
        echo "</td>";
        echo "<td>";
        echo $row['V14'];
        echo "</td>";
        echo "<td>";
        echo $row['V15'];
        echo "</td>";
        echo "<td>";
        echo $row['V16'];
        echo "</td>";
        echo "<td>";
        echo $row['V17'];
        echo "</td>";
        echo "<td>";
        echo $row['V18'];
        echo "</td>";
        echo "<td>";
        echo $row['V19'];
        echo "</td>";
        echo "<td>";
        echo $row['V20'];
        echo "</td>";
        echo "<td>";
        echo $row['V21'];
        echo "</td>";
        echo "<td>";
        echo $row['V22'];
        echo "</td>";
        echo "<td>";
        echo $row['V23'];
        echo "</td>";
        echo "<td>";
        echo $row['V24'];
        echo "</td>";
        echo "<td>";
        echo $row['V25'];
        echo "</td>";
        echo "<td>";
        echo $row['V26'];
        echo "</td>";
        echo "<td>";
        echo $row['V27'];
        echo "</td>";
        echo "<td>";
        echo $row['V28'];
        echo "</td>";
        echo "<td>";
        echo $row['V29'];
        echo "</td>";
        echo "<td>";
        echo $row['V30'];
        echo "</td>";
        echo "<td>";
        echo $row['V31'];
        echo "</td>";
        echo "<td>";
        echo $row['V32'];
        echo "</td>";
        echo "<td>";
        echo $row['V33'];
        echo "</td>";
        echo "<td>";
        echo $row['V34'];
        echo "</td>";
        echo "<td>";
        echo $row['V35'];
        echo "</td>";
        echo "<td>";
        echo $row['V36'];
        echo "</td>";
        echo "<td>";
        echo $row['V37'];
        echo "</td>";
        echo "<td>";
        echo $row['V38'];
        echo "</td>";
        echo "<td>";
        echo $row['V39'];
        echo "</td>";
        echo "<td>";
        echo $row['V40'];
        echo "</td>";
        echo "<td>";
        echo $row['V41'];
        echo "</td>";
        echo "<td>";
        echo $row['V42'];
        echo "</td>";
        echo "<td>";
        echo $row['V43'];
        echo "</td>";
        echo "<td>";
        echo $row['V44'];
        echo "</td>";
        echo "<td>";
        echo $row['V45'];
        echo "</td>";
        echo "<td>";
        echo $row['V46'];
        echo "</td>";
        echo "<td>";
        echo $row['V461'];
        echo "</td>";
        echo "<td>";
        echo $row['V462'];
        echo "</td>";
        echo "<td>";
        echo $row['V463'];
        echo "</td>";
        echo "<td>";
        echo $row['V464'];
        echo "</td>";
        echo "<td>";
        echo $row['V465'];
        echo "</td>";
        echo "<td>";
        echo $row['V466'];
        echo "</td>";
        echo "<td>";
        echo $row['V467'];
        echo "</td>";
        echo "<td>";
        echo $row['V468'];
        echo "</td>";
        echo "<td>";
        echo $row['V47'];
        echo "</td>";
        echo "<td>";
        echo $row['V48'];
        echo "</td>";
        echo "<td>";
        echo $row['V49'];
        echo "</td>";
        echo "<td>";
        echo $row['V50'];
        echo "</td>";
        echo "<td>";
        echo $row['V51'];
        echo "</td>";
        echo "<td>";
        echo $row['V52'];
        echo "</td>";
        echo "<td>";
        echo $row['V53'];
        echo "</td>";
        echo "<td>";
        echo $row['V531'];
        echo "</td>";
        echo "<td>";
        echo $row['V532'];
        echo "</td>";
        echo "<td>";
        echo $row['V533'];
        echo "</td>";
        echo "<td>";
        echo $row['V534'];
        echo "</td>";
        echo "<td>";
        echo $row['V535'];
        echo "</td>";
        echo "<td>";
        echo $row['V536'];
        echo "</td>";
        echo "<td>";
        echo $row['V537'];
        echo "</td>";
        echo "<td>";
        echo $row['V538'];
        echo "</td>";
        echo "<td>";
        echo $row['V539'];
        echo "</td>";
        echo "<td>";
        echo $row['V54'];
        echo "</td>";
        echo "<td>";
        echo $row['V55'];
        echo "</td>";
        echo "<td>";
        echo $row['V56'];
        echo "</td>";
        echo "<td>";
        echo $row['V57'];
        echo "</td>";
        echo "<td>";
        echo $row['V58'];
        echo "</td>";
        echo "<td>";
        echo $row['V59'];
        echo "</td>";
        echo "<td>";
        echo $row['V60'];
        echo "</td>";
        echo "<td>";
        echo $row['V61'];
        echo "</td>";
        echo "<td>";
        echo $row['V62'];
        echo "</td>";
        echo "<td>";
        echo $row['V63'];
        echo "</td>";
        echo "<td>";
        echo $row['V64'];
        echo "</td>";
        echo "<td>";
        echo $row['V65'];
        echo "</td>";
        echo "<td>";
        echo $row['V66'];
        echo "</td>";
        echo "<td>";
        echo $row['V661'];
        echo "</td>";
        echo "<td>";
        echo $row['V662'];
        echo "</td>";
        echo "<td>";
        echo $row['V663'];
        echo "</td>";
        echo "<td>";
        echo $row['V664'];
        echo "</td>";
        echo "<td>";
        echo $row['V665'];
        echo "</td>";
        echo "<td>";
        echo $row['V666'];
        echo "</td>";
        echo "<td>";
        echo $row['V667'];
        echo "</td>";
        echo "<td>";
        echo $row['V668'];
        echo "</td>";
        echo "<td>";
        echo $row['V669'];
        echo "</td>";
        echo "<td>";
        echo $row['V67'];
        echo "</td>";
        echo "<td>";
        echo $row['V68'];
        echo "</td>";
        echo "<td>";
        echo $row['V69'];
        echo "</td>";
        echo "<td>";
        echo $row['V70'];
        echo "</td>";
        echo "<td>";
        echo $row['V71'];
        echo "</td>";
        echo "<td>";
        echo $row['V72'];
        echo "</td>";
        echo "<td>";
        echo $row['V73'];
        echo "</td>";
        echo "<td>";
        echo $row['V74'];
        echo "</td>";
        echo "<td>";
        echo $row['V75'];
        echo "</td>";
        echo "<td>";
        echo $row['V76'];
        echo "</td>";
        echo "<td>";
        echo $row['V77'];
        echo "</td>";
        echo "<td>";
        echo $row['V78'];
        echo "</td>";
        echo "<td>";
        echo $row['V79'];
        echo "</td>";
        echo "<td>";
        echo $row['V80'];
        echo "</td>";
        echo "<td>";
        echo $row['V81'];
        echo "</td>";
        echo "<td>";
        echo $row['V82'];
        echo "</td>";
        echo "<td>";
        echo $row['V83'];
        echo "</td>";
        echo "<td>";
        echo $row['V84'];
        echo "</td>";
        echo "<td>";
        echo $row['V85'];
        echo "</td>";
        echo "<td>";
        echo $row['V86'];
        echo "</td>";
        echo "<td>";
        echo $row['V87'];
        echo "</td>";
        echo "<td>";
        echo $row['V88'];
        echo "</td>";
        echo "<td>";
        echo $row['V89'];
        echo "</td>";
        echo "<td>";
        echo $row['V90'];
        echo "</td>";
        echo "<td>";
        echo $row['V91'];
        echo "</td>";
        echo "<td>";
        echo $row['V92'];
        echo "</td>";
        echo "<td>";
        echo $row['V93'];
        echo "</td>";
        echo "<td>";
        echo $row['V94'];
        echo "</td>";
        echo "<td>";
        echo $row['V95'];
        echo "</td>";
        echo "<td>";
        echo $row['V96'];
        echo "</td>";
        echo "<td>";
        echo $row['V97'];
        echo "</td>";
        echo "<td>";
        echo $row['V98'];
        echo "</td>";
        echo "<td>";
        echo $row['V99'];
        echo "</td>";
        echo "<td>";
        echo $row['V100'];
        echo "</td>";
        echo "<td>";
        echo $row['V101'];
        echo "</td>";
        echo "<td>";
        echo $row['V102'];
        echo "</td>";
        echo "<td>";
        echo $row['V103'];
        echo "</td>";
        echo "<td>";
        echo $row['V104'];
        echo "</td>";
        echo "<td>";
        echo $row['V105'];
        echo "</td>";
        echo "<td>";
        echo $row['V106'];
        echo "</td>";
        echo "<td>";
        echo $row['V107'];
        echo "</td>";
        echo "<td>";
        echo $row['V108'];
        echo "</td>";
        echo "<td>";
        echo $row['V109'];
        echo "</td>";
        echo "<td>";
        echo $row['V110'];
        echo "</td>";
        echo "<td>";
        echo $row['V111'];
        echo "</td>";
        echo "<td>";
        echo $row['V112'];
        echo "</td>";
        echo "<td>";
        echo $row['V113'];
        echo "</td>";
        echo "<td>";
        echo $row['V114'];
        echo "</td>";
        echo "<td>";
        echo $row['V1141'];
        echo "</td>";
        echo "<td>";
        echo $row['V1142'];
        echo "</td>";
        echo "<td>";
        echo $row['V1143'];
        echo "</td>";
        echo "<td>";
        echo $row['V1144'];
        echo "</td>";
        echo "<td>";
        echo $row['V1145'];
        echo "</td>";
        echo "<td>";
        echo $row['V1146'];
        echo "</td>";
        echo "<td>";
        echo $row['V115'];
        echo "</td>";
        echo "<td>";
        echo $row['V116'];
        echo "</td>";
        echo "<td>";
        echo $row['V117'];
        echo "</td>";
        echo "<td>";
        echo $row['V118'];
        echo "</td>";
        echo "<td>";
        echo $row['V119'];
        echo "</td>";
        echo "<td>";
        echo $row['V120'];
        echo "</td>";
        echo "<td>";
        echo $row['V121'];
        echo "</td>";
        echo "<td>";
        echo $row['V122'];
        echo "</td>";
        echo "<td>";
        echo $row['V123'];
        echo "</td>";
        echo "<td>";
        echo $row['V124'];
        echo "</td>";
        echo "<td>";
        echo $row['V125'];
        echo "</td>";
        echo "<td>";
        echo $row['V126'];
        echo "</td>";
        echo "<td>";
        echo $row['V127'];
        echo "</td>";
        echo "<td>";
        echo $row['V128'];
        echo "</td>";
        echo "<td>";
        echo $row['V129'];
        echo "</td>";
        echo "<td>";
        echo $row['V130'];
        echo "</td>";
        echo "<td>";
        echo $row['V131'];
        echo "</td>";
        echo "<td>";
        echo $row['V132'];
        echo "</td>";
        echo "<td>";
        echo $row['V133'];
        echo "</td>";
        echo "<td>";
        echo $row['V134'];
        echo "</td>";
        echo "<td>";
        echo $row['V135'];
        echo "</td>";
        echo "<td>";
        echo $row['V136'];
        echo "</td>";
        echo "<td>";
        echo $row['V137'];
        echo "</td>";
        echo "<td>";
        echo $row['V138'];
        echo "</td>";
        echo "<td>";
        echo $row['V139'];
        echo "</td>";
        echo "<td>";
        echo $row['V140'];
        echo "</td>";
        echo "<td>";
        echo $row['V141'];
        echo "</td>";
        echo "<td>";
        echo $row['V142'];
        echo "</td>";
        echo "<td>";
        echo $row['V143'];
        echo "</td>";
        echo "<td>";
        echo $row['V144'];
        echo "</td>";
        echo "<td>";
        echo $row['V145'];
        echo "</td>";
        echo "<td>";
        echo $row['V146'];
        echo "</td>";
        echo "<td>";
        echo $row['V147'];
        echo "</td>";
        echo "<td>";
        echo $row['V148'];
        echo "</td>";
        echo "<td>";
        echo $row['V149'];
        echo "</td>";
        echo "<td>";
        echo $row['RESPONSABLE_ACTUAL'];
        echo "</td>";
        echo "<td>";
        echo $row['FECHA_REGISTRO'];
        echo "</td>";
        echo "<td>";
        echo $row['FECHA_MODIFICACION'];
        echo "</td>";
        echo "<td>";
        echo $row['CODIGO_SINIESTRO'];
        echo "</td>";
        echo "<td>";
        echo $row['TIPO_AFILIADO'];
        echo "</td>";
        echo "</tr>";
    }
    oci_close($c);
    ?>
</table>