<?php
require_once('../../config/dbcon.php');
header('Content-type: application/vnd.ms-excel');
header("Content-Disposition: attachment; filename=Matriz de asignacion de usuario" . "_" . date("dmY") . ".xls");
header("Pragma: no-cache");
header("Expires: 0");

$periodo = $_GET['periodo'];

$regimen = $_GET['regimen'];
if ($regimen == 'S') {
    $consulta = oci_parse($c, "SELECT PER_CAPITACION, NIT_PRESTADOR, NOM_PRESTADOR, D.NOM_DEPARTAMENTO, M.NOM_CIUDAD, TIP_REGIMEN, NUM_CONTRATO, COD_CENTROCOSTOS, TIP_SERVICIO,'01' GRUPO_ETAREO, '' DATOMOD
                                FROM  oasis.CAPITACIONMES C LEFT JOIN oasis.DEPARTAMENTO D ON SUBSTR(NUM_CAUSACION,1,2) = D.COD_DEPARTAMENTO
                                LEFT JOIN oasis.CIUDAD M ON NUM_CAUSACION = M.COD_DEPARTAMENTO || M.COD_CIUDAD 
                                INNER JOIN  oasis.ocnt_contrato CO ON CO.CNTN_NUMERO = NUM_CONTRATO AND
                                                                      CO.CNTC_DOCUMENTO = 'KS' AND CO.CNTC_ESTADO  ='P'
                                WHERE PER_CAPITACION    = :v_periodo
                                AND NUM_CAUSACION IN (SELECT COD_DEPARTAMENTO || COD_CIUDAD FROM oasis.CIUDADES_UNI WHERE UNICA ='N')
                                GROUP BY PER_CAPITACION, NIT_PRESTADOR, NOM_PRESTADOR, D.NOM_DEPARTAMENTO, M.NOM_CIUDAD, TIP_REGIMEN, NUM_CONTRATO, COD_CENTROCOSTOS, TIP_SERVICIO
                                UNION 

                                SELECT PER_CAPITACION, NIT_PRESTADOR, NOM_PRESTADOR, D.NOM_DEPARTAMENTO, M.NOM_CIUDAD, TIP_REGIMEN, NUM_CONTRATO, COD_CENTROCOSTOS, TIP_SERVICIO,'02' GRUPO_ETAREO, '' DATOMOD
                                FROM  oasis.CAPITACIONMES C LEFT JOIN oasis.DEPARTAMENTO D ON SUBSTR(NUM_CAUSACION,1,2) = D.COD_DEPARTAMENTO                            
                                LEFT JOIN oasis.CIUDAD M ON NUM_CAUSACION = M.COD_DEPARTAMENTO || M.COD_CIUDAD 
                                INNER JOIN  oasis.ocnt_contrato CO ON CO.CNTN_NUMERO = NUM_CONTRATO AND
                                                                      CO.CNTC_DOCUMENTO = 'KS' AND CO.CNTC_ESTADO  ='P'
                                WHERE PER_CAPITACION    = :v_periodo
                                AND NUM_CAUSACION IN (SELECT COD_DEPARTAMENTO || COD_CIUDAD FROM oasis.CIUDADES_UNI WHERE UNICA ='N')
                                GROUP BY PER_CAPITACION, NIT_PRESTADOR, NOM_PRESTADOR, D.NOM_DEPARTAMENTO, M.NOM_CIUDAD, TIP_REGIMEN, NUM_CONTRATO, COD_CENTROCOSTOS, TIP_SERVICIO
                                UNION
                                
                                SELECT PER_CAPITACION, NIT_PRESTADOR, NOM_PRESTADOR, D.NOM_DEPARTAMENTO, M.NOM_CIUDAD, TIP_REGIMEN, NUM_CONTRATO, COD_CENTROCOSTOS, TIP_SERVICIO,'03' GRUPO_ETAREO, '' DATOMOD
                                FROM  oasis.CAPITACIONMES C LEFT JOIN oasis.DEPARTAMENTO D ON SUBSTR(NUM_CAUSACION,1,2) = D.COD_DEPARTAMENTO
                                LEFT JOIN oasis.CIUDAD M ON NUM_CAUSACION = M.COD_DEPARTAMENTO || M.COD_CIUDAD 
                                INNER JOIN  oasis.ocnt_contrato CO ON CO.CNTN_NUMERO = NUM_CONTRATO AND
                                                                                                CO.CNTC_DOCUMENTO = 'KS' AND CO.CNTC_ESTADO  ='P'
                                WHERE PER_CAPITACION    = :v_periodo
                                AND NUM_CAUSACION IN (SELECT COD_DEPARTAMENTO || COD_CIUDAD FROM oasis.CIUDADES_UNI WHERE UNICA ='N')
                                GROUP BY PER_CAPITACION, NIT_PRESTADOR, NOM_PRESTADOR, D.NOM_DEPARTAMENTO, M.NOM_CIUDAD, TIP_REGIMEN, NUM_CONTRATO, COD_CENTROCOSTOS, TIP_SERVICIO
                                UNION

                                SELECT PER_CAPITACION, NIT_PRESTADOR, NOM_PRESTADOR, D.NOM_DEPARTAMENTO, M.NOM_CIUDAD, TIP_REGIMEN, NUM_CONTRATO, COD_CENTROCOSTOS, TIP_SERVICIO,'04' GRUPO_ETAREO, '' DATOMOD
                                FROM  oasis.CAPITACIONMES C LEFT JOIN oasis.DEPARTAMENTO D ON SUBSTR(NUM_CAUSACION,1,2) = D.COD_DEPARTAMENTO
                                LEFT JOIN oasis.CIUDAD M ON NUM_CAUSACION = M.COD_DEPARTAMENTO || M.COD_CIUDAD 
                                INNER JOIN  oasis.ocnt_contrato CO ON CO.CNTN_NUMERO = NUM_CONTRATO AND
                                                                                                CO.CNTC_DOCUMENTO = 'KS' AND CO.CNTC_ESTADO  ='P'
                                WHERE PER_CAPITACION    = :v_periodo
                                AND NUM_CAUSACION IN (SELECT COD_DEPARTAMENTO || COD_CIUDAD FROM oasis.CIUDADES_UNI WHERE UNICA ='N')
                                GROUP BY PER_CAPITACION, NIT_PRESTADOR, NOM_PRESTADOR, D.NOM_DEPARTAMENTO, M.NOM_CIUDAD, TIP_REGIMEN, NUM_CONTRATO, COD_CENTROCOSTOS, TIP_SERVICIO
                                UNION

                                SELECT PER_CAPITACION, NIT_PRESTADOR, NOM_PRESTADOR, D.NOM_DEPARTAMENTO, M.NOM_CIUDAD, TIP_REGIMEN, NUM_CONTRATO, COD_CENTROCOSTOS, TIP_SERVICIO,'05' GRUPO_ETAREO, '' DATOMOD
                                FROM  oasis.CAPITACIONMES C LEFT JOIN oasis.DEPARTAMENTO D ON SUBSTR(NUM_CAUSACION,1,2) = D.COD_DEPARTAMENTO
                                LEFT JOIN oasis.CIUDAD M ON NUM_CAUSACION = M.COD_DEPARTAMENTO || M.COD_CIUDAD 
                                                                INNER JOIN  oasis.ocnt_contrato CO ON CO.CNTN_NUMERO = NUM_CONTRATO AND
                                                                                                CO.CNTC_DOCUMENTO = 'KS' AND CO.CNTC_ESTADO  ='P'
                                WHERE PER_CAPITACION    = :v_periodo
                                AND NUM_CAUSACION IN (SELECT COD_DEPARTAMENTO || COD_CIUDAD FROM oasis.CIUDADES_UNI WHERE UNICA ='N')
                                GROUP BY PER_CAPITACION, NIT_PRESTADOR, NOM_PRESTADOR, D.NOM_DEPARTAMENTO, M.NOM_CIUDAD, TIP_REGIMEN, NUM_CONTRATO, COD_CENTROCOSTOS, TIP_SERVICIO
                                UNION

                                SELECT PER_CAPITACION, NIT_PRESTADOR, NOM_PRESTADOR, D.NOM_DEPARTAMENTO, M.NOM_CIUDAD, TIP_REGIMEN, NUM_CONTRATO, COD_CENTROCOSTOS, TIP_SERVICIO,'06' GRUPO_ETAREO, '' DATOMOD
                                FROM  oasis.CAPITACIONMES C LEFT JOIN oasis.DEPARTAMENTO D ON SUBSTR(NUM_CAUSACION,1,2) = D.COD_DEPARTAMENTO
                                LEFT JOIN oasis.CIUDAD M ON NUM_CAUSACION = M.COD_DEPARTAMENTO || M.COD_CIUDAD 
                                                                INNER JOIN  oasis.ocnt_contrato CO ON CO.CNTN_NUMERO = NUM_CONTRATO AND
                                                                                                CO.CNTC_DOCUMENTO = 'KS' AND CO.CNTC_ESTADO  ='P'
                                WHERE PER_CAPITACION    = :v_periodo
                                AND NUM_CAUSACION IN (SELECT COD_DEPARTAMENTO || COD_CIUDAD FROM oasis.CIUDADES_UNI WHERE UNICA ='N')
                                GROUP BY PER_CAPITACION, NIT_PRESTADOR, NOM_PRESTADOR, D.NOM_DEPARTAMENTO, M.NOM_CIUDAD, TIP_REGIMEN, NUM_CONTRATO, COD_CENTROCOSTOS, TIP_SERVICIO
                                UNION 

                                SELECT PER_CAPITACION, NIT_PRESTADOR, NOM_PRESTADOR, D.NOM_DEPARTAMENTO, M.NOM_CIUDAD, TIP_REGIMEN, NUM_CONTRATO, COD_CENTROCOSTOS, TIP_SERVICIO,'07' GRUPO_ETAREO, '' DATOMOD
                                FROM  oasis.CAPITACIONMES C LEFT JOIN oasis.DEPARTAMENTO D ON SUBSTR(NUM_CAUSACION,1,2) = D.COD_DEPARTAMENTO
                                LEFT JOIN oasis.CIUDAD M ON NUM_CAUSACION = M.COD_DEPARTAMENTO || M.COD_CIUDAD 
                                                                INNER JOIN  oasis.ocnt_contrato CO ON CO.CNTN_NUMERO = NUM_CONTRATO AND
                                                                                                CO.CNTC_DOCUMENTO = 'KS' AND CO.CNTC_ESTADO  ='P'
                                WHERE PER_CAPITACION    = :v_periodo
                                AND NUM_CAUSACION IN (SELECT COD_DEPARTAMENTO || COD_CIUDAD FROM oasis.CIUDADES_UNI WHERE UNICA ='N')
                                GROUP BY PER_CAPITACION, NIT_PRESTADOR, NOM_PRESTADOR, D.NOM_DEPARTAMENTO, M.NOM_CIUDAD, TIP_REGIMEN, NUM_CONTRATO, COD_CENTROCOSTOS, TIP_SERVICIO
                                UNION 

                                SELECT PER_CAPITACION, NIT_PRESTADOR, NOM_PRESTADOR, D.NOM_DEPARTAMENTO, M.NOM_CIUDAD, TIP_REGIMEN, NUM_CONTRATO, COD_CENTROCOSTOS, TIP_SERVICIO,'08' GRUPO_ETAREO, '' DATOMOD
                                FROM  oasis.CAPITACIONMES C LEFT JOIN oasis.DEPARTAMENTO D ON SUBSTR(NUM_CAUSACION,1,2) = D.COD_DEPARTAMENTO
                                LEFT JOIN oasis.CIUDAD M ON NUM_CAUSACION = M.COD_DEPARTAMENTO || M.COD_CIUDAD 
                                                                INNER JOIN  oasis.ocnt_contrato CO ON CO.CNTN_NUMERO = NUM_CONTRATO AND
                                                                                                CO.CNTC_DOCUMENTO = 'KS' AND CO.CNTC_ESTADO  ='P'
                                WHERE PER_CAPITACION    = :v_periodo
                                AND NUM_CAUSACION IN (SELECT COD_DEPARTAMENTO || COD_CIUDAD FROM oasis.CIUDADES_UNI WHERE UNICA ='N')
                                GROUP BY PER_CAPITACION, NIT_PRESTADOR, NOM_PRESTADOR, D.NOM_DEPARTAMENTO, M.NOM_CIUDAD, TIP_REGIMEN, NUM_CONTRATO, COD_CENTROCOSTOS, TIP_SERVICIO
                                UNION 

                                SELECT PER_CAPITACION, NIT_PRESTADOR, NOM_PRESTADOR, D.NOM_DEPARTAMENTO, M.NOM_CIUDAD, TIP_REGIMEN, NUM_CONTRATO, COD_CENTROCOSTOS, TIP_SERVICIO,'09' GRUPO_ETAREO, '' DATOMOD
                                FROM  oasis.CAPITACIONMES C LEFT JOIN oasis.DEPARTAMENTO D ON SUBSTR(NUM_CAUSACION,1,2) = D.COD_DEPARTAMENTO
                                LEFT JOIN oasis.CIUDAD M ON NUM_CAUSACION = M.COD_DEPARTAMENTO || M.COD_CIUDAD 
                                                                INNER JOIN  oasis.ocnt_contrato CO ON CO.CNTN_NUMERO = NUM_CONTRATO AND
                                                                                                CO.CNTC_DOCUMENTO = 'KS' AND CO.CNTC_ESTADO  ='P'
                                WHERE PER_CAPITACION    = :v_periodo
                                AND NUM_CAUSACION IN (SELECT COD_DEPARTAMENTO || COD_CIUDAD FROM oasis.CIUDADES_UNI WHERE UNICA ='N')
                                GROUP BY PER_CAPITACION, NIT_PRESTADOR, NOM_PRESTADOR, D.NOM_DEPARTAMENTO, M.NOM_CIUDAD, TIP_REGIMEN, NUM_CONTRATO, COD_CENTROCOSTOS, TIP_SERVICIO
                                UNION 

                                SELECT PER_CAPITACION, NIT_PRESTADOR, NOM_PRESTADOR, D.NOM_DEPARTAMENTO, M.NOM_CIUDAD, TIP_REGIMEN, NUM_CONTRATO, COD_CENTROCOSTOS, TIP_SERVICIO,'10' GRUPO_ETAREO, '' DATOMOD
                                FROM  oasis.CAPITACIONMES C LEFT JOIN oasis.DEPARTAMENTO D ON SUBSTR(NUM_CAUSACION,1,2) = D.COD_DEPARTAMENTO
                                LEFT JOIN oasis.CIUDAD M ON NUM_CAUSACION = M.COD_DEPARTAMENTO || M.COD_CIUDAD 
                                                                INNER JOIN  oasis.ocnt_contrato CO ON CO.CNTN_NUMERO = NUM_CONTRATO AND
                                                                                                CO.CNTC_DOCUMENTO = 'KS' AND CO.CNTC_ESTADO  ='P'
                                WHERE PER_CAPITACION    = :v_periodo
                                AND NUM_CAUSACION IN (SELECT COD_DEPARTAMENTO || COD_CIUDAD FROM oasis.CIUDADES_UNI WHERE UNICA ='N')
                                GROUP BY PER_CAPITACION, NIT_PRESTADOR, NOM_PRESTADOR, D.NOM_DEPARTAMENTO, M.NOM_CIUDAD, TIP_REGIMEN, NUM_CONTRATO, COD_CENTROCOSTOS, TIP_SERVICIO
                                UNION

                                SELECT PER_CAPITACION, NIT_PRESTADOR, NOM_PRESTADOR, D.NOM_DEPARTAMENTO, M.NOM_CIUDAD, TIP_REGIMEN, NUM_CONTRATO, COD_CENTROCOSTOS, TIP_SERVICIO,'11' GRUPO_ETAREO, '' DATOMOD
                                FROM  oasis.CAPITACIONMES C LEFT JOIN oasis.DEPARTAMENTO D ON SUBSTR(NUM_CAUSACION,1,2) = D.COD_DEPARTAMENTO
                                LEFT JOIN oasis.CIUDAD M ON NUM_CAUSACION = M.COD_DEPARTAMENTO || M.COD_CIUDAD 
                                                                INNER JOIN  oasis.ocnt_contrato CO ON CO.CNTN_NUMERO = NUM_CONTRATO AND
                                                                                                CO.CNTC_DOCUMENTO = 'KS' AND CO.CNTC_ESTADO  ='P'
                                WHERE PER_CAPITACION    = :v_periodo
                                AND NUM_CAUSACION IN (SELECT COD_DEPARTAMENTO || COD_CIUDAD FROM oasis.CIUDADES_UNI WHERE UNICA ='N')
                                GROUP BY PER_CAPITACION, NIT_PRESTADOR, NOM_PRESTADOR, D.NOM_DEPARTAMENTO, M.NOM_CIUDAD, TIP_REGIMEN, NUM_CONTRATO, COD_CENTROCOSTOS, TIP_SERVICIO
                                UNION 
                                SELECT PER_CAPITACION, NIT_PRESTADOR, NOM_PRESTADOR, D.NOM_DEPARTAMENTO, M.NOM_CIUDAD, TIP_REGIMEN, NUM_CONTRATO, COD_CENTROCOSTOS, TIP_SERVICIO,'12' GRUPO_ETAREO, '' DATOMOD
                                FROM  oasis.CAPITACIONMES C LEFT JOIN oasis.DEPARTAMENTO D ON SUBSTR(NUM_CAUSACION,1,2) = D.COD_DEPARTAMENTO
                                LEFT JOIN oasis.CIUDAD M ON NUM_CAUSACION = M.COD_DEPARTAMENTO || M.COD_CIUDAD 
                                                                INNER JOIN  oasis.ocnt_contrato CO ON CO.CNTN_NUMERO = NUM_CONTRATO AND
                                                                                                CO.CNTC_DOCUMENTO = 'KS' AND CO.CNTC_ESTADO  ='P'
                                WHERE PER_CAPITACION    = :v_periodo
                                AND NUM_CAUSACION IN (SELECT COD_DEPARTAMENTO || COD_CIUDAD FROM oasis.CIUDADES_UNI WHERE UNICA ='N')
                                GROUP BY PER_CAPITACION, NIT_PRESTADOR, NOM_PRESTADOR, D.NOM_DEPARTAMENTO, M.NOM_CIUDAD, TIP_REGIMEN, NUM_CONTRATO, COD_CENTROCOSTOS, TIP_SERVICIO
                                UNION
                                SELECT PER_CAPITACION, NIT_PRESTADOR, NOM_PRESTADOR, D.NOM_DEPARTAMENTO, M.NOM_CIUDAD, TIP_REGIMEN, NUM_CONTRATO, COD_CENTROCOSTOS, TIP_SERVICIO,'13' GRUPO_ETAREO, '' DATOMOD
                                FROM  oasis.CAPITACIONMES C LEFT JOIN oasis.DEPARTAMENTO D ON SUBSTR(NUM_CAUSACION,1,2) = D.COD_DEPARTAMENTO
                                LEFT JOIN oasis.CIUDAD M ON NUM_CAUSACION = M.COD_DEPARTAMENTO || M.COD_CIUDAD 
                                                                INNER JOIN  oasis.ocnt_contrato CO ON CO.CNTN_NUMERO = NUM_CONTRATO AND
                                                                                                CO.CNTC_DOCUMENTO = 'KS' AND CO.CNTC_ESTADO  ='P'
                                WHERE PER_CAPITACION    = :v_periodo
                                AND NUM_CAUSACION IN (SELECT COD_DEPARTAMENTO || COD_CIUDAD FROM oasis.CIUDADES_UNI WHERE UNICA ='N')
                                GROUP BY PER_CAPITACION, NIT_PRESTADOR, NOM_PRESTADOR, D.NOM_DEPARTAMENTO, M.NOM_CIUDAD, TIP_REGIMEN, NUM_CONTRATO, COD_CENTROCOSTOS, TIP_SERVICIO
                                UNION
                                SELECT PER_CAPITACION, NIT_PRESTADOR, NOM_PRESTADOR, D.NOM_DEPARTAMENTO, M.NOM_CIUDAD, TIP_REGIMEN, NUM_CONTRATO, COD_CENTROCOSTOS, TIP_SERVICIO,'14' GRUPO_ETAREO, '' DATOMOD
                                FROM  oasis.CAPITACIONMES C LEFT JOIN oasis.DEPARTAMENTO D ON SUBSTR(NUM_CAUSACION,1,2) = D.COD_DEPARTAMENTO
                                LEFT JOIN oasis.CIUDAD M ON NUM_CAUSACION = M.COD_DEPARTAMENTO || M.COD_CIUDAD 
                                                                INNER JOIN  oasis.ocnt_contrato CO ON CO.CNTN_NUMERO = NUM_CONTRATO AND
                                                                                                CO.CNTC_DOCUMENTO = 'KS' AND CO.CNTC_ESTADO  ='P'
                                WHERE PER_CAPITACION    = :v_periodo
                                AND NUM_CAUSACION IN (SELECT COD_DEPARTAMENTO || COD_CIUDAD FROM oasis.CIUDADES_UNI WHERE UNICA ='N')
                                GROUP BY PER_CAPITACION, NIT_PRESTADOR, NOM_PRESTADOR, D.NOM_DEPARTAMENTO, M.NOM_CIUDAD, TIP_REGIMEN, NUM_CONTRATO, COD_CENTROCOSTOS, TIP_SERVICIO");


    //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

} else {
    $consulta = oci_parse($c, "SELECT PER_CAPITACION, NIT_PRESTADOR, NOM_PRESTADOR, D.NOM_DEPARTAMENTO, M.NOM_CIUDAD, TIP_REGIMEN, NUM_CONTRATO, COD_CENTROCOSTOS, TIP_SERVICIO,'01' GRUPO_ETAREO, '' DATOMOD
                                FROM  oasis.CAPITACIONMES C LEFT JOIN oasis.DEPARTAMENTO D ON SUBSTR(NUM_CAUSACION,1,2) = D.COD_DEPARTAMENTO
                                LEFT JOIN oasis.CIUDAD M ON NUM_CAUSACION = M.COD_DEPARTAMENTO || M.COD_CIUDAD 
                                INNER JOIN  oasis.ocnt_contrato CO ON CO.CNTN_NUMERO = NUM_CONTRATO AND
                                                                    CO.CNTC_DOCUMENTO = 'KC' AND CO.CNTC_ESTADO  ='P'
                                WHERE PER_CAPITACION    = :v_periodo
                                AND NUM_CAUSACION IN (SELECT COD_DEPARTAMENTO || COD_CIUDAD FROM oasis.CIUDADES_UNI WHERE UNICA ='N')
                                GROUP BY PER_CAPITACION, NIT_PRESTADOR, NOM_PRESTADOR, D.NOM_DEPARTAMENTO, M.NOM_CIUDAD, TIP_REGIMEN, NUM_CONTRATO, COD_CENTROCOSTOS, TIP_SERVICIO
                                UNION 

    SELECT PER_CAPITACION, NIT_PRESTADOR, NOM_PRESTADOR, D.NOM_DEPARTAMENTO, M.NOM_CIUDAD, TIP_REGIMEN, NUM_CONTRATO, COD_CENTROCOSTOS, TIP_SERVICIO,'02' GRUPO_ETAREO, '' DATOMOD
    FROM  oasis.CAPITACIONMES C LEFT JOIN oasis.DEPARTAMENTO D ON SUBSTR(NUM_CAUSACION,1,2) = D.COD_DEPARTAMENTO                            
    LEFT JOIN oasis.CIUDAD M ON NUM_CAUSACION = M.COD_DEPARTAMENTO || M.COD_CIUDAD 
    INNER JOIN  oasis.ocnt_contrato CO ON CO.CNTN_NUMERO = NUM_CONTRATO AND
                                          CO.CNTC_DOCUMENTO = 'KC' AND CO.CNTC_ESTADO  ='P'
    WHERE PER_CAPITACION    = :v_periodo
    AND NUM_CAUSACION IN (SELECT COD_DEPARTAMENTO || COD_CIUDAD FROM oasis.CIUDADES_UNI WHERE UNICA ='N')
    GROUP BY PER_CAPITACION, NIT_PRESTADOR, NOM_PRESTADOR, D.NOM_DEPARTAMENTO, M.NOM_CIUDAD, TIP_REGIMEN, NUM_CONTRATO, COD_CENTROCOSTOS, TIP_SERVICIO
    UNION
    
SELECT PER_CAPITACION, NIT_PRESTADOR, NOM_PRESTADOR, D.NOM_DEPARTAMENTO, M.NOM_CIUDAD, TIP_REGIMEN, NUM_CONTRATO, COD_CENTROCOSTOS, TIP_SERVICIO,'03' GRUPO_ETAREO, '' DATOMOD
FROM  oasis.CAPITACIONMES C LEFT JOIN oasis.DEPARTAMENTO D ON SUBSTR(NUM_CAUSACION,1,2) = D.COD_DEPARTAMENTO
LEFT JOIN oasis.CIUDAD M ON NUM_CAUSACION = M.COD_DEPARTAMENTO || M.COD_CIUDAD 
INNER JOIN  oasis.ocnt_contrato CO ON CO.CNTN_NUMERO = NUM_CONTRATO AND
                                          CO.CNTC_DOCUMENTO = 'KC' AND CO.CNTC_ESTADO  ='P'
WHERE PER_CAPITACION    = :v_periodo
AND NUM_CAUSACION IN (SELECT COD_DEPARTAMENTO || COD_CIUDAD FROM oasis.CIUDADES_UNI WHERE UNICA ='N')
GROUP BY PER_CAPITACION, NIT_PRESTADOR, NOM_PRESTADOR, D.NOM_DEPARTAMENTO, M.NOM_CIUDAD, TIP_REGIMEN, NUM_CONTRATO, COD_CENTROCOSTOS, TIP_SERVICIO
UNION

SELECT PER_CAPITACION, NIT_PRESTADOR, NOM_PRESTADOR, D.NOM_DEPARTAMENTO, M.NOM_CIUDAD, TIP_REGIMEN, NUM_CONTRATO, COD_CENTROCOSTOS, TIP_SERVICIO,'04' GRUPO_ETAREO, '' DATOMOD
FROM  oasis.CAPITACIONMES C LEFT JOIN oasis.DEPARTAMENTO D ON SUBSTR(NUM_CAUSACION,1,2) = D.COD_DEPARTAMENTO
LEFT JOIN oasis.CIUDAD M ON NUM_CAUSACION = M.COD_DEPARTAMENTO || M.COD_CIUDAD 
INNER JOIN  oasis.ocnt_contrato CO ON CO.CNTN_NUMERO = NUM_CONTRATO AND
                                          CO.CNTC_DOCUMENTO = 'KC' AND CO.CNTC_ESTADO  ='P'
WHERE PER_CAPITACION    = :v_periodo
AND NUM_CAUSACION IN (SELECT COD_DEPARTAMENTO || COD_CIUDAD FROM oasis.CIUDADES_UNI WHERE UNICA ='N')
GROUP BY PER_CAPITACION, NIT_PRESTADOR, NOM_PRESTADOR, D.NOM_DEPARTAMENTO, M.NOM_CIUDAD, TIP_REGIMEN, NUM_CONTRATO, COD_CENTROCOSTOS, TIP_SERVICIO
UNION

SELECT PER_CAPITACION, NIT_PRESTADOR, NOM_PRESTADOR, D.NOM_DEPARTAMENTO, M.NOM_CIUDAD, TIP_REGIMEN, NUM_CONTRATO, COD_CENTROCOSTOS, TIP_SERVICIO,'05' GRUPO_ETAREO, '' DATOMOD
FROM  oasis.CAPITACIONMES C LEFT JOIN oasis.DEPARTAMENTO D ON SUBSTR(NUM_CAUSACION,1,2) = D.COD_DEPARTAMENTO
        LEFT JOIN oasis.CIUDAD M ON NUM_CAUSACION = M.COD_DEPARTAMENTO || M.COD_CIUDAD 
        INNER JOIN  oasis.ocnt_contrato CO ON CO.CNTN_NUMERO = NUM_CONTRATO AND
                                          CO.CNTC_DOCUMENTO = 'KC' AND CO.CNTC_ESTADO  ='P'
WHERE PER_CAPITACION    = :v_periodo
AND NUM_CAUSACION IN (SELECT COD_DEPARTAMENTO || COD_CIUDAD FROM oasis.CIUDADES_UNI WHERE UNICA ='N')
GROUP BY PER_CAPITACION, NIT_PRESTADOR, NOM_PRESTADOR, D.NOM_DEPARTAMENTO, M.NOM_CIUDAD, TIP_REGIMEN, NUM_CONTRATO, COD_CENTROCOSTOS, TIP_SERVICIO
UNION

SELECT PER_CAPITACION, NIT_PRESTADOR, NOM_PRESTADOR, D.NOM_DEPARTAMENTO, M.NOM_CIUDAD, TIP_REGIMEN, NUM_CONTRATO, COD_CENTROCOSTOS, TIP_SERVICIO,'06' GRUPO_ETAREO, '' DATOMOD
FROM  oasis.CAPITACIONMES C LEFT JOIN oasis.DEPARTAMENTO D ON SUBSTR(NUM_CAUSACION,1,2) = D.COD_DEPARTAMENTO
        LEFT JOIN oasis.CIUDAD M ON NUM_CAUSACION = M.COD_DEPARTAMENTO || M.COD_CIUDAD 
        INNER JOIN  oasis.ocnt_contrato CO ON CO.CNTN_NUMERO = NUM_CONTRATO AND
                                          CO.CNTC_DOCUMENTO = 'KC' AND CO.CNTC_ESTADO  ='P'
WHERE PER_CAPITACION    = :v_periodo
AND NUM_CAUSACION IN (SELECT COD_DEPARTAMENTO || COD_CIUDAD FROM oasis.CIUDADES_UNI WHERE UNICA ='N')
GROUP BY PER_CAPITACION, NIT_PRESTADOR, NOM_PRESTADOR, D.NOM_DEPARTAMENTO, M.NOM_CIUDAD, TIP_REGIMEN, NUM_CONTRATO, COD_CENTROCOSTOS, TIP_SERVICIO
UNION 

SELECT PER_CAPITACION, NIT_PRESTADOR, NOM_PRESTADOR, D.NOM_DEPARTAMENTO, M.NOM_CIUDAD, TIP_REGIMEN, NUM_CONTRATO, COD_CENTROCOSTOS, TIP_SERVICIO,'07' GRUPO_ETAREO, '' DATOMOD
FROM  oasis.CAPITACIONMES C LEFT JOIN oasis.DEPARTAMENTO D ON SUBSTR(NUM_CAUSACION,1,2) = D.COD_DEPARTAMENTO
        LEFT JOIN oasis.CIUDAD M ON NUM_CAUSACION = M.COD_DEPARTAMENTO || M.COD_CIUDAD 
        INNER JOIN  oasis.ocnt_contrato CO ON CO.CNTN_NUMERO = NUM_CONTRATO AND
                                          CO.CNTC_DOCUMENTO = 'KC' AND CO.CNTC_ESTADO  ='P'
WHERE PER_CAPITACION    = :v_periodo
AND NUM_CAUSACION IN (SELECT COD_DEPARTAMENTO || COD_CIUDAD FROM oasis.CIUDADES_UNI WHERE UNICA ='N')
GROUP BY PER_CAPITACION, NIT_PRESTADOR, NOM_PRESTADOR, D.NOM_DEPARTAMENTO, M.NOM_CIUDAD, TIP_REGIMEN, NUM_CONTRATO, COD_CENTROCOSTOS, TIP_SERVICIO
UNION 

SELECT PER_CAPITACION, NIT_PRESTADOR, NOM_PRESTADOR, D.NOM_DEPARTAMENTO, M.NOM_CIUDAD, TIP_REGIMEN, NUM_CONTRATO, COD_CENTROCOSTOS, TIP_SERVICIO,'08' GRUPO_ETAREO, '' DATOMOD
FROM  oasis.CAPITACIONMES C LEFT JOIN oasis.DEPARTAMENTO D ON SUBSTR(NUM_CAUSACION,1,2) = D.COD_DEPARTAMENTO
        LEFT JOIN oasis.CIUDAD M ON NUM_CAUSACION = M.COD_DEPARTAMENTO || M.COD_CIUDAD 
        INNER JOIN  oasis.ocnt_contrato CO ON CO.CNTN_NUMERO = NUM_CONTRATO AND
                                          CO.CNTC_DOCUMENTO = 'KC' AND CO.CNTC_ESTADO  ='P'
WHERE PER_CAPITACION    = :v_periodo
AND NUM_CAUSACION IN (SELECT COD_DEPARTAMENTO || COD_CIUDAD FROM oasis.CIUDADES_UNI WHERE UNICA ='N')
GROUP BY PER_CAPITACION, NIT_PRESTADOR, NOM_PRESTADOR, D.NOM_DEPARTAMENTO, M.NOM_CIUDAD, TIP_REGIMEN, NUM_CONTRATO, COD_CENTROCOSTOS, TIP_SERVICIO
UNION 

SELECT PER_CAPITACION, NIT_PRESTADOR, NOM_PRESTADOR, D.NOM_DEPARTAMENTO, M.NOM_CIUDAD, TIP_REGIMEN, NUM_CONTRATO, COD_CENTROCOSTOS, TIP_SERVICIO,'09' GRUPO_ETAREO, '' DATOMOD
FROM  oasis.CAPITACIONMES C LEFT JOIN oasis.DEPARTAMENTO D ON SUBSTR(NUM_CAUSACION,1,2) = D.COD_DEPARTAMENTO
        LEFT JOIN oasis.CIUDAD M ON NUM_CAUSACION = M.COD_DEPARTAMENTO || M.COD_CIUDAD 
        INNER JOIN  oasis.ocnt_contrato CO ON CO.CNTN_NUMERO = NUM_CONTRATO AND
                                          CO.CNTC_DOCUMENTO = 'KC' AND CO.CNTC_ESTADO  ='P'
WHERE PER_CAPITACION    = :v_periodo
AND NUM_CAUSACION IN (SELECT COD_DEPARTAMENTO || COD_CIUDAD FROM oasis.CIUDADES_UNI WHERE UNICA ='N')
GROUP BY PER_CAPITACION, NIT_PRESTADOR, NOM_PRESTADOR, D.NOM_DEPARTAMENTO, M.NOM_CIUDAD, TIP_REGIMEN, NUM_CONTRATO, COD_CENTROCOSTOS, TIP_SERVICIO
UNION 

SELECT PER_CAPITACION, NIT_PRESTADOR, NOM_PRESTADOR, D.NOM_DEPARTAMENTO, M.NOM_CIUDAD, TIP_REGIMEN, NUM_CONTRATO, COD_CENTROCOSTOS, TIP_SERVICIO,'10' GRUPO_ETAREO, '' DATOMOD
FROM  oasis.CAPITACIONMES C LEFT JOIN oasis.DEPARTAMENTO D ON SUBSTR(NUM_CAUSACION,1,2) = D.COD_DEPARTAMENTO
        LEFT JOIN oasis.CIUDAD M ON NUM_CAUSACION = M.COD_DEPARTAMENTO || M.COD_CIUDAD 
        INNER JOIN  oasis.ocnt_contrato CO ON CO.CNTN_NUMERO = NUM_CONTRATO AND
                                          CO.CNTC_DOCUMENTO = 'KC' AND CO.CNTC_ESTADO  ='P'
WHERE PER_CAPITACION    = :v_periodo
AND NUM_CAUSACION IN (SELECT COD_DEPARTAMENTO || COD_CIUDAD FROM oasis.CIUDADES_UNI WHERE UNICA ='N')
GROUP BY PER_CAPITACION, NIT_PRESTADOR, NOM_PRESTADOR, D.NOM_DEPARTAMENTO, M.NOM_CIUDAD, TIP_REGIMEN, NUM_CONTRATO, COD_CENTROCOSTOS, TIP_SERVICIO
UNION
SELECT PER_CAPITACION, NIT_PRESTADOR, NOM_PRESTADOR, D.NOM_DEPARTAMENTO, M.NOM_CIUDAD, TIP_REGIMEN, NUM_CONTRATO, COD_CENTROCOSTOS, TIP_SERVICIO,'11' GRUPO_ETAREO, '' DATOMOD
FROM  oasis.CAPITACIONMES C LEFT JOIN oasis.DEPARTAMENTO D ON SUBSTR(NUM_CAUSACION,1,2) = D.COD_DEPARTAMENTO
        LEFT JOIN oasis.CIUDAD M ON NUM_CAUSACION = M.COD_DEPARTAMENTO || M.COD_CIUDAD 
        INNER JOIN  oasis.ocnt_contrato CO ON CO.CNTN_NUMERO = NUM_CONTRATO AND
                                          CO.CNTC_DOCUMENTO = 'KC' AND CO.CNTC_ESTADO  ='P'
WHERE PER_CAPITACION    = :v_periodo
AND NUM_CAUSACION IN (SELECT COD_DEPARTAMENTO || COD_CIUDAD FROM oasis.CIUDADES_UNI WHERE UNICA ='N')
GROUP BY PER_CAPITACION, NIT_PRESTADOR, NOM_PRESTADOR, D.NOM_DEPARTAMENTO, M.NOM_CIUDAD, TIP_REGIMEN, NUM_CONTRATO, COD_CENTROCOSTOS, TIP_SERVICIO
UNION 
SELECT PER_CAPITACION, NIT_PRESTADOR, NOM_PRESTADOR, D.NOM_DEPARTAMENTO, M.NOM_CIUDAD, TIP_REGIMEN, NUM_CONTRATO, COD_CENTROCOSTOS, TIP_SERVICIO,'12' GRUPO_ETAREO, '' DATOMOD
FROM  oasis.CAPITACIONMES C LEFT JOIN oasis.DEPARTAMENTO D ON SUBSTR(NUM_CAUSACION,1,2) = D.COD_DEPARTAMENTO
        LEFT JOIN oasis.CIUDAD M ON NUM_CAUSACION = M.COD_DEPARTAMENTO || M.COD_CIUDAD 
        INNER JOIN  oasis.ocnt_contrato CO ON CO.CNTN_NUMERO = NUM_CONTRATO AND
                                          CO.CNTC_DOCUMENTO = 'KC' AND CO.CNTC_ESTADO  ='P'
WHERE PER_CAPITACION    = :v_periodo
AND NUM_CAUSACION IN (SELECT COD_DEPARTAMENTO || COD_CIUDAD FROM oasis.CIUDADES_UNI WHERE UNICA ='N')
GROUP BY PER_CAPITACION, NIT_PRESTADOR, NOM_PRESTADOR, D.NOM_DEPARTAMENTO, M.NOM_CIUDAD, TIP_REGIMEN, NUM_CONTRATO, COD_CENTROCOSTOS, TIP_SERVICIO
UNION
SELECT PER_CAPITACION, NIT_PRESTADOR, NOM_PRESTADOR, D.NOM_DEPARTAMENTO, M.NOM_CIUDAD, TIP_REGIMEN, NUM_CONTRATO, COD_CENTROCOSTOS, TIP_SERVICIO,'13' GRUPO_ETAREO, '' DATOMOD
FROM  oasis.CAPITACIONMES C LEFT JOIN oasis.DEPARTAMENTO D ON SUBSTR(NUM_CAUSACION,1,2) = D.COD_DEPARTAMENTO
        LEFT JOIN oasis.CIUDAD M ON NUM_CAUSACION = M.COD_DEPARTAMENTO || M.COD_CIUDAD 
        INNER JOIN  oasis.ocnt_contrato CO ON CO.CNTN_NUMERO = NUM_CONTRATO AND
                                          CO.CNTC_DOCUMENTO = 'KC' AND CO.CNTC_ESTADO  ='P'
WHERE PER_CAPITACION    = :v_periodo
AND NUM_CAUSACION IN (SELECT COD_DEPARTAMENTO || COD_CIUDAD FROM oasis.CIUDADES_UNI WHERE UNICA ='N')
GROUP BY PER_CAPITACION, NIT_PRESTADOR, NOM_PRESTADOR, D.NOM_DEPARTAMENTO, M.NOM_CIUDAD, TIP_REGIMEN, NUM_CONTRATO, COD_CENTROCOSTOS, TIP_SERVICIO
UNION
SELECT PER_CAPITACION, NIT_PRESTADOR, NOM_PRESTADOR, D.NOM_DEPARTAMENTO, M.NOM_CIUDAD, TIP_REGIMEN, NUM_CONTRATO, COD_CENTROCOSTOS, TIP_SERVICIO,'14' GRUPO_ETAREO, '' DATOMOD
FROM  oasis.CAPITACIONMES C LEFT JOIN oasis.DEPARTAMENTO D ON SUBSTR(NUM_CAUSACION,1,2) = D.COD_DEPARTAMENTO
        LEFT JOIN oasis.CIUDAD M ON NUM_CAUSACION = M.COD_DEPARTAMENTO || M.COD_CIUDAD 
        INNER JOIN  oasis.ocnt_contrato CO ON CO.CNTN_NUMERO = NUM_CONTRATO AND
                                          CO.CNTC_DOCUMENTO = 'KC' AND CO.CNTC_ESTADO  ='P'
WHERE PER_CAPITACION    = :v_periodo
AND NUM_CAUSACION IN (SELECT COD_DEPARTAMENTO || COD_CIUDAD FROM oasis.CIUDADES_UNI WHERE UNICA ='N')
GROUP BY PER_CAPITACION, NIT_PRESTADOR, NOM_PRESTADOR, D.NOM_DEPARTAMENTO, M.NOM_CIUDAD, TIP_REGIMEN, NUM_CONTRATO, COD_CENTROCOSTOS, TIP_SERVICIO");
}


oci_bind_by_name($consulta, ':v_periodo', $periodo);





?>

<table cellspacing="0" cellpadding="0" border="1" align="center">
    <!--// Aqui va el encabezado del reporte, reemplazar solo los nombres de las columnas-->
    <tr>
        <th align='center'>PERIODO DE CAPITA</th>
        <th align='center'>NIT</th>
        <th align='center'>RAZON SOCIAL</th>
        <th align='center'>DEPARTAMENTO</th>
        <th align='center'>CIUDAD</th>
        <th align='center'>REGIMEN</th>
        <th align='center'>CONTRATO</th>
        <th align='center'>CENTRO DE COSTOS</th>
        <th align='center'>TIPOS DE SERVICIO</th>
        <th align='center'>GRUPO ETARIO</th>
        <th align='center'>CAMPO A DIGITAR</th>


    </tr>

    <?php

    oci_execute($consulta);

    // Se recorre el array con los resultados obtenidos de la base de datos
    while ($rows = oci_fetch_assoc($consulta)) {
        echo "<tr>";
        echo "<td align='center'>";
        echo $rows['PER_CAPITACION'];
        echo "</td>";
        echo "<td align='center'>";
        echo $rows['NIT_PRESTADOR'];
        echo "</td>";
        echo "<td align='center'>";
        echo $rows['NOM_PRESTADOR'];
        echo "</td>";
        echo "<td align='center'>";
        echo $rows['NOM_DEPARTAMENTO'];
        echo "</td>";
        echo "<td align='center'>";
        echo $rows['NOM_CIUDAD'];
        echo "</td>";
        echo "<td align='center'>";
        echo $rows['TIP_REGIMEN'];
        echo "</td>";
        echo "<td align='center'>";
        echo $rows['NUM_CONTRATO'];
        echo "</td>";
        echo "<td align='center'>";
        echo $rows['COD_CENTROCOSTOS'];
        echo "</td>";
        echo "<td align='center'>";
        echo $rows['TIP_SERVICIO'];
        echo "</td>";
        echo "<td align='center'>";
        echo $rows['GRUPO_ETAREO'];
        echo "</td>";
        echo "<td align='center'>";
        echo $rows['DATOMOD'];
        echo "</td>";




        echo "</tr>";
    }

    print_r(error_get_last());

    oci_close($c);

    ?>